<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Intervention\Image\Laravel\Facades\Image;

class ProductoSeeder extends Seeder
{
    public function run() {
        DB::table('productos')->insert([
            [
                'nombre' => 'SIS Energy Electrolyte',
                'marca' => 'SIS',
                'especificacion' => 'Proporciona energía rápida y repone electrolitos esenciales para mantener el rendimiento durante el ejercicio intenso. ',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_SISPinkGrapefruit.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 10,
            ],[
                'nombre' => 'SIS Energy Electrolyte',
                'marca' => 'SIS',
                'especificacion' => 'Proporciona energía rápida y repone electrolitos esenciales para mantener el rendimiento durante el ejercicio intenso. ',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_SISFruitSalad.webp'))),
                'codigo_barras' => '',
                'destacado' => True,
                'cantidad' => 10,
            ],[
                'nombre' => 'SIS Energy Electrolyte',
                'marca' => 'SIS',
                'especificacion' => 'Proporciona energía rápida y repone electrolitos esenciales para mantener el rendimiento durante el ejercicio intenso. ',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_SISLemon&Lime.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 10,
            ],[
                'nombre' => 'Cannondale Bicicleta',
                'marca' => 'Cannondale',
                'especificacion' => 'Diseñada para terrenos exigentes, cuenta con 8 velocidades y componentes Shimano que ofrecen cambios precisos y duraderos. Su marco de aluminio garantiza ligereza y resistencia, mientras que la suspensión SR Suntour y los frenos hidráulicos brindan control y confort en cualquier camino.',
                'subcategoria' => 'Bici 1 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Trail Seven',
                'precio' => 388000,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_CannondaleRojo.webp'))),
                'codigo_barras' => '',
                'destacado' => True,
                'cantidad' => 1,
            ],[
                'nombre' => 'Scott Bicicleta',
                'marca' => 'Scott',
                'especificacion' => 'Equipada con transmisión Sram 1x12 para un rendimiento preciso, suspensión RockShox que absorbe cualquier terreno y frenos hidráulicos de alta potencia para un control total. Ideal para conquistar senderos exigentes con confianza y durabilidad.',
                'subcategoria' => 'Bici 2 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Scale 970',
                'precio' => 599600,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_BicicletaScottNegra.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'nombre' => 'Flypony Bicicleta',
                'marca' => 'Euro',
                'especificacion' => 'Bicicleta para niña 20 en colores morado y blanco: divertida y segura, con detalles encantadores en la manivela que añaden un toque especial. Diseñada para brindar comodidad y estabilidad, perfecta para acompañar sus aventuras al aire libre',
                'subcategoria' => 'Bici 3 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Flypony',
                'precio' => 71900,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_BicicletaEuroFlypony.webp'))),
                'codigo_barras' => '',
                'destacado' => True,
                'cantidad' => 2,
            ],[
                'nombre' => 'Calory Guantes',
                'marca' => 'Garneu',
                'especificacion' => 'Protección y comodidad en cada movimiento, diseñados con materiales transpirables y ajuste ergonómico. Ideales para deportes o entrenamientos intensivos, ofrecen un excelente agarre y resistencia al desgaste',
                'subcategoria' => 'Guantes',
                'categoria' => 'Ropa',
                'modelo' => 'Calory',
                'precio' => 11200,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_GuantesGarneuCalory.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 5,
            ],[
                'nombre' => 'Maxxis Llanta',
                'marca' => 'Maxxis',
                'especificacion' => 'Llanta Crossmark 29 para bicicleta: diseñada específicamente para terrenos con suelo suelto y seco, ofrece un excelente agarre y control. Su banda de rodadura central mejora la velocidad en superficies duras, mientras que los tacos laterales proporcionan estabilidad y tracción en condiciones desafiantes',
                'subcategoria' => 'Llanta',
                'categoria' => 'Repuestos',
                'modelo' => 'Crossmark',
                'precio' => 9300,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_LlantaMaxxisCrossMark.webp'))),
                'codigo_barras' => '',
                'destacado' => true,
                'cantidad' => 3,
            ],[
                'nombre' => 'WD-40',
                'marca' => 'WD-40',
                'especificacion' => 'Aceite WD-40 para cadenas: formulado especialmente para proteger y lubricar en temporada lluviosa. Su fórmula resistente al agua reduce el desgaste y previene la corrosión, asegurando un pedaleo suave y una cadena en óptimas condiciones bajo la lluvia',
                'subcategoria' => 'Aceite',
                'categoria' => 'Repuestos',
                'modelo' => 'Bike Wet Chain Lube',
                'precio' => 3350,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_WD-40.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 6,
            ],[
                'nombre' => 'Cable de freno Favarcia',
                'marca' => 'Favarcia',
                'especificacion' => 'Cable de freno trasero: fabricado para ofrecer una respuesta precisa y confiable en cada frenada. Ideal para reemplazo o mantenimiento, asegura una conducción segura y un control óptimo en todo tipo de terrenos.',
                'subcategoria' => 'Cable',
                'categoria' => 'Repuestos',
                'modelo' => '',
                'precio' => 650,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_CableFrenoFavarcia.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 20,
            ],[
                'nombre' => 'Medias XPedition',
                'marca' => 'XPedition',
                'especificacion' => 'Medias unisex en color azul con cintas reflectivas en el tobillo: diseñadas para combinar estilo y seguridad, ideales para actividades al aire libre o uso urbano. Su tejido cómodo y duradero ofrece un ajuste perfecto, mientras que las cintas reflectivas mejoran la visibilidad en condiciones de poca luz',
                'subcategoria' => 'Ropa',
                'categoria' => 'Medias',
                'modelo' => 'Reflective',
                'precio' => 7000,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_MediasXPeditionAzul.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Casco Scott',
                'marca' => 'Scott',
                'especificacion' => 'Casco gris de alta calidad con tecnología MIPS: diseñado para brindar una protección superior en deportes de alto impacto. Su sistema MIPS reduce las fuerzas de rotación en caso de impacto, ofreciendo una capa extra de seguridad y confianza en cada aventura',
                'subcategoria' => 'Ropa',
                'categoria' => 'Casco',
                'modelo' => 'Arx Plus',
                'precio' => 65000,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_CascoScottGris.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'nombre' => 'Casco Scott',
                'marca' => 'Scott',
                'especificacion' => 'Casco deportivo azul de gran calidad: diseñado para brindar máxima protección y comodidad durante tus actividades deportivas. Su estructura resistente y ajuste ergonómico aseguran seguridad y estabilidad en cada movimiento',
                'subcategoria' => 'Ropa',
                'categoria' => 'Casco',
                'modelo' => 'Arx Plus',
                'precio' => 48000,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_CascoScottAzul.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'nombre' => 'Suspensión Recon',
                'marca' => 'RockShox',
                'especificacion' => 'Suspensión RockShox 29 con cámara de aire y tubos de acero inoxidable: diseñada para ofrecer un rendimiento superior en terrenos exigentes. Su cámara de aire garantiza una respuesta suave y ajustable, mientras que los tubos de acero inoxidable brindan durabilidad y resistencia a la corrosión',
                'subcategoria' => 'Suspensión',
                'categoria' => 'Piezas',
                'modelo' => 'Recon',
                'precio' => 138700,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_SuspensionRockShox.webp'))),
                'codigo_barras' => '',
                'destacado' => true,
                'cantidad' => 2,
            ],[
                'nombre' => 'Road Comp BOA',
                'marca' => 'Scott',
                'especificacion' => 'Zapato de ruta en negro y plata: combina estilo y rendimiento para ciclistas exigentes. Su diseño aerodinámico y suela rígida optimizan la transferencia de potencia, mientras que su ajuste preciso asegura comodidad en cada kilómetro',
                'subcategoria' => 'Ropa',
                'categoria' => 'Zapato',
                'modelo' => 'Road Comp BOA',
                'precio' => 86200,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_ZapatoScott.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 3,
            ],[
                'nombre' => 'Calzado XC1',
                'marca' => 'Shimano',
                'especificacion' => 'Zapato de ciclismo para montaña: diseñado para brindar tracción y soporte en terrenos difíciles. Su suela robusta y antideslizante asegura un agarre óptimo tanto en el pedal como al caminar en superficies irregulares, mientras que su ajuste ergonómico proporciona comodidad y estabilidad en cada recorrido',
                'subcategoria' => 'Ropa',
                'categoria' => 'Zapato',
                'modelo' => 'XC1',
                'precio' => 54000,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_ZapatoShimano.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 7,
            ],[
                'nombre' => 'Luz Sprinter',
                'marca' => 'Sprinter',
                'especificacion' => 'Luz delantera recargable de 400 lúmenes: potente y adaptable a cualquier bicicleta, ilumina el camino con claridad y seguridad. Su diseño compacto y su fácil sistema de montaje permiten un ajuste rápido, ideal para trayectos nocturnos o condiciones de baja visibilidad',
                'subcategoria' => 'Accesorios',
                'categoria' => 'Luz',
                'modelo' => 'Aurora 400',
                'precio' => 7500,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_LuzSprinterRecargable.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Llave Fixit 13',
                'marca' => 'Sprinter',
                'especificacion' => 'Herramienta multifuncional con 12 llaves: ideal para el mantenimiento de tu bicicleta, diseñada en un formato delgado y compacto que facilita su transporte. Incluye las llaves esenciales para ajustes y reparaciones rápidas, ofreciendo funcionalidad y conveniencia en un solo dispositivo',
                'subcategoria' => 'Herramientas',
                'categoria' => 'Llave',
                'modelo' => 'Fixit 13',
                'precio' => 12250,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_Fixit13Sprinter.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Llave Fixit 15',
                'marca' => 'Sprinter',
                'especificacion' => 'Herramienta multifuncional de 12 llaves: diseñada para realizar el mantenimiento completo de tu bicicleta. Incluye todas las llaves esenciales para ajustes rápidos y precisos, ideal para ciclistas que buscan una solución práctica y compacta para el cuidado de su equipo',
                'subcategoria' => 'Herramientas',
                'categoria' => 'Llave',
                'modelo' => 'Fixit 15',
                'precio' => 8150,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_Fixit15Sprinter.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Pasador Tiagra',
                'marca' => 'Shimano',
                'especificacion' => 'Pasador de cambios de 11 velocidades para bicicleta de ruta: optimiza la precisión y rapidez en cada cambio de marcha. Diseñado específicamente para el rendimiento en rutas, garantiza una transmisión suave y confiable, ideal para ciclistas que buscan eficiencia en sus recorridos',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Pasador',
                'modelo' => 'Tiagra',
                'precio' => 37300,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_TiagraShimano.webp'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Pasador Sram',
                'marca' => 'Sram',
                'especificacion' => 'Pasador de cambios de 12 velocidades para bicicleta de montaña: diseñado para cambios suaves y precisos en terrenos exigentes. Su construcción robusta asegura durabilidad y rendimiento óptimo, ideal para ciclistas de montaña que buscan confiabilidad y control en cada ascenso y descenso',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Pasador',
                'modelo' => 'Sx',
                'precio' => 60800,
                'imagen' => "data:image/webp;base64,".base64_encode(file_get_contents(public_path('images/productos/producto_SxSram.webp'))),
                'codigo_barras' => '',
                'destacado' => True,
                'cantidad' => 2,
            ],[
                'nombre' => 'Porta anfora Giant',
                'marca' => 'Giant',
                'especificacion' => 'Soporte ligero y resistente, diseñado para asegurar tu botella en cualquier terreno. Perfecto para ciclistas que buscan accesibilidad y durabilidad en cada recorrido.',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Accesorios',
                'modelo' => 'Airway Sport',
                'precio' => 6900,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Porta anfora Giant.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Ánfora termica Polar',
                'marca' => 'Polar',
                'especificacion' => 'Mantiene tus bebidas frías por más tiempo gracias a su aislamiento avanzado. Diseñada para ciclistas, combina durabilidad y fácil acceso en cada recorrido.',
                'subcategoria' => '',
                'categoria' => 'Accesorios',
                'modelo' => 'Ánfora Polar',
                'precio' => 7700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/ANFORA POLAR TÉRMICA.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Ánfora térmica Zéfal',
                'marca' => 'Zéfal',
                'especificacion' => 'Diseñada para mantener tus bebidas frías por más tiempo, con doble pared aislante y materiales duraderos. Perfecta para acompañarte en cualquier ruta y resistir las demandas del ciclismo.',
                'subcategoria' => '',
                'categoria' => 'Accesorios',
                'modelo' => 'Ánfora  Zéfalca',
                'precio' => 7000,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/ANFORA TÉRMICA zefal.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Soporte muñequera',
                'marca' => 'Everest',
                'especificacion' => 'Diseñado para brindar estabilidad y soporte a la muñeca, ideal para actividades deportivas o para la recuperación de lesiones. Fabricado con materiales transpirables y ajustables para un ajuste cómodo y seguro.',
                'subcategoria' => 'Salud',
                'categoria' => 'Accesorios',
                'modelo' => 'Soporte Muñequera',
                'precio' => 2650,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/muñequera elastica everlast.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Balón Volleyball',
                'marca' => 'Fit2',
                'especificacion' => 'Perfecto para un rendimiento óptimo en cada jugada, con una construcción duradera que soporta el uso en interiores y exteriores. Su superficie suave y diseño balanceado garantizan un toque preciso y control superior.',
                'subcategoria' => '',
                'categoria' => 'Deporte',
                'modelo' => 'Balon Volleyball',
                'precio' => 10000,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Balon voleiball fit2.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Electrolit Mora Azul',
                'marca' => 'Electrolit',
                'especificacion' => 'Bebida hidratante con electrolitos, sabor mora azul, especialmente formulada para reponer líquidos y tratar la deshidratación.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Electrolit Mora Azul',
                'precio' => 1950,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Electrolit_MoraAzul.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Electrolit Maracuya',
                'marca' => 'Electrolit',
                'especificacion' => 'Bebida hidratante con electrolitos, sabor maracuya, especialmente formulada para reponer líquidos y tratar la deshidratación.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Electrolit Maracuya',
                'precio' => 1950,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Electrolit_Maracuya.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Electrolit Uva',
                'marca' => 'Electrolit',
                'especificacion' => 'Bebida hidratante con electrolitos, sabor mora uva, especialmente formulada para reponer líquidos y tratar la deshidratación.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Electrolit Uva',
                'precio' => 1950,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Electrolit_Uva.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Roar Organic Fresa Limonada',
                'marca' => 'Roar',
                'especificacion' => 'Bebida refrescante y baja en calorías, con electrolitos y vitaminas del grupo B para una hidratación natural. Delicioso sabor a fresa con un toque de limonada, perfecto para recargar energías de manera saludable.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Roar Organic',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Roar Organic Fresa.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Rooster Zero Sandia',
                'marca' => 'Rooster',
                'especificacion' => 'Energizante natural, cero calorías, diseñado para mejorar el desempeño físico y mental. Contiene cafeína lo cual eleva tu energía por 4 horas. Adicionalmente contiene electrolitos lo cual ayuda a reponer las sales minerales perdidas.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Rooster Zero Sandia',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Rooster_Sandia_Zero.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Rooster Zero Limonada-Fresa',
                'marca' => 'Rooster',
                'especificacion' => 'Energizante natural, cero calorías, diseñado para mejorar el desempeño físico y mental. Contiene cafeína lo cual eleva tu energía por 4 horas. Adicionalmente contiene electrolitos lo cual ayuda a reponer las sales minerales perdidas.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Rooster Zero Limonada-Fresa',
                'precio' => 1650,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Rooster_LimonadaFresaZero.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Puños ESI Grips Verde',
                'marca' => 'ESIGrips',
                'especificacion' => 'Cómodos y resistentes, ofrecen un agarre antideslizante para mayor control en cualquier terreno.',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Accesorios',
                'modelo' => 'Chunky',
                'precio' => 16000,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/ChunkyGreen.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Puños de bicicleta de silicona',
                'marca' => 'ESIGrips',
                'especificacion' => 'Estos puños cómodos y duraderos son una mejora que brindará comodidad a todos tus viajes.',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Accesorios',
                'modelo' => 'Plush Silicone',
                'precio' => 13400,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/plushsiliconebicyclegrips.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => "Fit CR (Combinación Chunky/Racer's Edge)",
                'marca' => 'ESIGrips',
                'especificacion' => 'Los puños ergonómicos Fit de ESI están diseñados para una posición completamente natural de la mano en el manillar.',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Repuestos',
                'modelo' => 'Fit XC',
                'precio' => 19950,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/FitCR_Combinatio.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Limited Edition - Tan',
                'marca' => 'ESIGrips',
                'especificacion' => 'Puños de color de edición limitada. Esta es una empuñadura de color de edición limitada disponible en Extra Chunky,',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Repuestos',
                'modelo' => 'Extra Chunky',
                'precio' => 12400,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Extra_Chunky_Limited_Edition.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Electrolit Fresa',
                'marca' => 'Rooster',
                'especificacion' => 'Bebida hidratante con electrolitos, sabor mora fresa, especialmente formulada para reponer líquidos y tratar la deshidratación.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Electrolit Fresa',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Electrolit_Fresa.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Rooster Naranja',
                'marca' => 'Rooster',
                'especificacion' => 'Energizante natural, cero calorías, diseñado para mejorar el desempeño físico y mental. Contiene cafeína lo cual eleva tu energía por 4 horas. Adicionalmente aporta Vitamina C para fortalecer el sistema inmune.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Rooster Naranja',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Rooster_Naranja.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Rooster Coco',
                'marca' => 'Rooster',
                'especificacion' => 'Energizante natural, cero calorías, diseñado para mejorar el desempeño físico y mental. Contiene cafeína lo cual eleva tu energía por 4 horas.',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Rooster Coco',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Rooster_Coco.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'nombre' => 'Rooster Manzana Verde',
                'marca' => 'Rooster',
                'especificacion' => 'Energizante natural, cero calorías, diseñado para mejorar el desemepeño físico y mental. Contiene cafeína lo cual eleva tu energía por 4 horas. ',
                'subcategoria' => 'Hidratacion',
                'categoria' => 'Alimentos',
                'modelo' => 'Rooster Manzana Verde',
                'precio' => 1700,
                'imagen' => "data:image/png;base64,".base64_encode(file_get_contents(public_path('images/productos/Rooster_ManzanaVerde.png'))),
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],
        ]);
    }
}
