<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run() {
        DB::table('productos')->insert([
            [
                'marca' => 'SIS',
                'especificacion' => 'Gel SIS con electrolitos sabor Pink Grapefruit de 60ml',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => 'images/productos/producto_SISPinkGrapefruit.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 10,
            ],[
                'marca' => 'SIS',
                'especificacion' => 'Gel SIS con electrolitos sabor Fruit Salad de 60ml',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => 'images/productos/producto_SISFruitSalad.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 10,
            ],[
                'marca' => 'SIS',
                'especificacion' => 'Gel SIS con electrolitos sabor Lemon & Lime de 60ml',
                'subcategoria' => 'Gel',
                'categoria' => 'Suplemento',
                'modelo' => 'Energy+Electrolyte',
                'precio' => 2700,
                'imagen' => 'images/productos/producto_SISLemon&Lime.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 10,
            ],[
                'marca' => 'Cannondale',
                'especificacion' => 'Bicicleta 29" Cannondale color rojo, especial para montaña de 8 velocidades, montada con componentes Shimano, marco de aluminio, frenos hidraulicos, suspensión SrSuntor',
                'subcategoria' => 'Bici 1 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Trail Seven',
                'precio' => 388000,
                'imagen' => 'images/productos/producto_CannondaleRojo.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'marca' => 'Scott',
                'especificacion' => 'Bicicleta 29" negra con detalles rojos marca Scott especial para montaña, componentes Sram 12x1, suspensión RockShox, frenos hidraulicos',
                'subcategoria' => 'Bici 2 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Scale 970',
                'precio' => 599600,
                'imagen' => 'images/productos/producto_BicicletaScottNegra.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'marca' => 'Euro',
                'especificacion' => 'Bicicleta niña 20" color morado y blanco con adornos en la manivela',
                'subcategoria' => 'Bici 3 sc',
                'categoria' => 'Bicicleta',
                'modelo' => 'Flypony',
                'precio' => 71900,
                'imagen' => 'images/productos/producto_BicicletaEuroFlypony.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Garneu',
                'especificacion' => 'Guantes cortos color negro-gris ',
                'subcategoria' => 'Guantes',
                'categoria' => 'Ropa',
                'modelo' => 'Calory',
                'precio' => 11200,
                'imagen' => 'images/productos/producto_GuantesGarneuCalory.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 5,
            ],[
                'marca' => 'Nite Rider',
                'especificacion' => 'Luz recargable delantera de 300 lumens para acoplar en la bicicleta, especial para esos rides nocturnos, además de ser resistente al agua posee diversos modos de iluminación',
                'subcategoria' => 'Luz',
                'categoria' => 'Accesorios',
                'modelo' => 'Swift 300',
                'precio' => 15750,
                'imagen' => 'images/productos/Falta.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 3,
            ],[
                'marca' => 'Maxxis',
                'especificacion' => 'Llanta crossmark para bicicleta 29" especial para agarre en los terrenos con suelo suelto y seco',
                'subcategoria' => 'Llanta',
                'categoria' => 'Repuestos',
                'modelo' => 'Crossmark',
                'precio' => 9300,
                'imagen' => 'images/productos/producto_LlantaMaxxisCrossMark.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 3,
            ],[
                'marca' => 'WD-40',
                'especificacion' => 'Aceite WD-40 especial para tu cadena en temporada lluviosa ',
                'subcategoria' => 'Aceite',
                'categoria' => 'Repuestos',
                'modelo' => 'Bike Wet Chain Lube',
                'precio' => 3350,
                'imagen' => 'images/productos/producto_WD-40.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 6,
            ],[
                'marca' => 'Favarcia',
                'especificacion' => 'Cable de freno trasero',
                'subcategoria' => 'Cable',
                'categoria' => 'Repuestos',
                'modelo' => '',
                'precio' => 650,
                'imagen' => 'images/productos/producto_CableFrenoFavarcia.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 20,
            ],[
                'marca' => 'XPedition',
                'especificacion' => 'Medias unisex color azul con cintas reflectivas en el tobillo',
                'subcategoria' => 'Ropa',
                'categoria' => 'Medias',
                'modelo' => 'Reflective',
                'precio' => 7000,
                'imagen' => 'images/productos/producto_MediasXPeditionAzul.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Scott',
                'especificacion' => 'Casco gris de alta calidad con teconología MIPS para esa protección necesaria a la hora de realizar deporte',
                'subcategoria' => 'Ropa',
                'categoria' => 'Casco',
                'modelo' => 'Arx Plus',
                'precio' => 65000,
                'imagen' => 'images/productos/producto_CascoScottGris.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'marca' => 'Scott',
                'especificacion' => 'Casco color azul de gran calidad para protegerte a la hora de realizar deporte',
                'subcategoria' => 'Ropa',
                'categoria' => 'Casco',
                'modelo' => 'Arx Plus',
                'precio' => 48000,
                'imagen' => 'images/productos/producto_CascoScottAzul.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 1,
            ],[
                'marca' => 'RockShox',
                'especificacion' => 'Suspensión 29" RockShox con cámara de aire tubos de acero inoxidable',
                'subcategoria' => 'Suspensión',
                'categoria' => 'Piezas',
                'modelo' => 'Recon',
                'precio' => 138700,
                'imagen' => 'images/productos/producto_SuspensionRockShox.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Scott',
                'especificacion' => 'Zapato de ruta color negro-plata',
                'subcategoria' => 'Ropa',
                'categoria' => 'Zapato',
                'modelo' => 'Road Comp BOA',
                'precio' => 86200,
                'imagen' => 'images/productos/producto_ZapatoScott.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 3,
            ],[
                'marca' => 'Shimano',
                'especificacion' => 'Zapato de ciclismo para montaña ',
                'subcategoria' => 'Ropa',
                'categoria' => 'Zapato',
                'modelo' => 'XC1',
                'precio' => 54000,
                'imagen' => 'images/productos/producto_ZapatoShimano.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 7,
            ],[
                'marca' => 'Sprinter',
                'especificacion' => 'Luz recargable delantera de 400 lumens adaptable a la bicicleta',
                'subcategoria' => 'Accesorios',
                'categoria' => 'Luz',
                'modelo' => 'Aurora 400',
                'precio' => 7500,
                'imagen' => 'images/productos/producto_LuzSprinterRecargable.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Sprinter',
                'especificacion' => 'Herramienta especial con 12 tipos de llaves especial para darle ese mantenimiento a la bicicleta con un diseño delgado',
                'subcategoria' => 'Herramientas',
                'categoria' => 'Llave',
                'modelo' => 'Fixit 13',
                'precio' => 12250,
                'imagen' => 'images/productos/producto_Fixit13Sprinter.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Sprinter',
                'especificacion' => 'Herramienta especial con 12 tipos de llaves especial para darle ese mantenimiento a la bicicleta',
                'subcategoria' => 'Herramientas',
                'categoria' => 'Llave',
                'modelo' => 'Fixit 15',
                'precio' => 8150,
                'imagen' => 'images/productos/producto_Fixit15Sprinter.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Shimano',
                'especificacion' => 'Pasador de cambios de 11 velocidades para bicicleta de ruta',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Pasador',
                'modelo' => 'Tiagra',
                'precio' => 37300,
                'imagen' => 'images/productos/producto_TiagraShimano.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],[
                'marca' => 'Sram',
                'especificacion' => 'Pasador de cambios de 12 velocidades para bicicleta de montaña',
                'subcategoria' => 'Repuestos',
                'categoria' => 'Pasador',
                'modelo' => 'Sx',
                'precio' => 60800,
                'imagen' => 'images/productos/producto_SxSram.png',
                'codigo_barras' => '',
                'destacado' => false,
                'cantidad' => 2,
            ],
        ]);
    }
}
